language: c

matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      compiler: gcc
      env:
        - LDFLAGS=
    - os: linux
      compiler: gcc
      env:
        - LDFLAGS=-static
    - os: linux
      compiler: clang
      env:
        - LDFLAGS=
    - os: linux
      compiler: clang
      env:
        - LDFLAGS=-static
    - os: linux
      compiler: musl-gcc
      env:
        - LDFLAGS=
      addons:
        apt:
          packages:
            - musl-tools
    - os: linux
      compiler: musl-gcc
      env:
        - LDFLAGS=-static
      addons:
        apt:
          packages:
            - musl-tools
    - arch: ppc64le
    - arch: arm64
    - arch: s390x

install:

script: make

notifications:
  irc: "irc.oftc.net#zeitmuehle"
